set parent_id when overwriting metadata.parent_uid
mitodl/ocw-studio pull request #1115
Opened 2022-03-11 21:39 UTC by ChristopherChudzicki

#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
This is a followup to https://github.com/mitodl/ocw-to-hugo/issues/482, toward #1041 

#### What's this PR do?
When using `overwrite_ocw_course_content` to import `metadata.parent_uid`, also set `parent_id`.

#### How should this be manually tested?

1. Have `mas-962-special-topics-new-textiles-spring-2010` locally
2. Inspect WebsiteContent object `b4c023d4-6c9a-bffc-eb02-09357443a4ef` in the admin panel
3. Observe that it has `metadata.parent_title` but no `metadata.parent_uid` or `parent` 
4. Run `docker-compose run --rm web python manage.py overwrite_ocw_course_content --bucket ocw-to-hugo-output-qa  --content-field="metadata.parent_uid" --filter mas-962-special-topics-new-textiles-spring-2010`
5. Inspect the WebsiteContent object again and observe that it now has *both* `metadata.parent_uid` and `parent`. 

If you do not have `mas-962-special-topics-new-textiles-spring-2010` locally, do the above with any object that has metadata `parent_title` but not `parent_uid`. There are lots.

2022-03-11 22:23 UTC, ChristopherChudzicki commented on ocw_import/api.py
> +            content_file.parent_id = content_data["parent"].id
This is the real change. I moved this all to a separate function partly for sanity and partly to appease the linting gods.

2022-03-16 15:16 UTC, mbertrand requested changes
When I initially imported `mas-962-special-topics-new-textiles-spring-2010` on master branch with the `import_ocw_course_sites` command, the resource `b4c023d4-6c9a-bffc-eb02-09357443a4ef` already had a populated `parent_uid` and `parent`:

<img width="835" alt="Screen Shot 2022-03-16 at 9 51 04 AM" src="https://user-images.githubusercontent.com/187676/158606880-166902d6-0e68-446e-8981-84fd3e4abdb1.png">

So I'm not sure how this resource got to its current state on RC/prod.  But with this PR, `overwrite_ocw_course_content` does populate `parent` if it isn't already, unlike before.

Unless this needs to go out ASAP, might be good to add a unit test for `update_content_from_s3_data ` to verify that `parent` is populated if `update_field` = "parent_uid"

2022-03-21 12:36 UTC, pdpinch commented
Assigning this back to Chris since it's "waiting on author"

2022-03-21 13:01 UTC, mbertrand commented
@pdpinch typically it remains assigned to the reviewer, just the label switches back and forth between "needs review" and "waiting on author"

2022-03-24 19:50 UTC, ChristopherChudzicki commented on ocw_import/api_test.py
> +class TestUpdateContentFromS3Data:
@mbertrand Let me know if you have any suggestions about this test. 

I wanted to be fairly explicit with assertions (e.g., assert against literals not computed expected dictionaries) but also wanted to not copy paste bunch of stuff between tests, hence the shared setup is in this class.

The `update_ocw2hugo_content` function which is more directly used by the management commands still has no tests, but at least this is something :/

2022-03-25 13:47 UTC, mbertrand approved these changes
Looks good to me including tests 👍

2022-03-25 13:49 UTC, merged