Cc/link parser and resolveuid
mitodl/ocw-studio pull request #1154
Opened 2022-03-22 19:45 UTC by ChristopherChudzicki

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
- [ ] Migrations
  - [ ] Migration is backwards-compatible with current production code
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested
- [ ] Settings
  - [ ] New settings are documented and present in `app.json`
  - [ ] New settings have reasonable development defaults, if applicable
  - [ ] Opened issue for DevOps regarding necessary configuration changes to deployed environments

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

#### Screenshots (if appropriate)
(Optional)

#### What GIF best describes this PR or how it makes you feel?
(Optional)

2022-03-22 19:50 UTC, ChristopherChudzicki commented on websites/management/commands/markdown_cleaning/parsing_utils.py
> +class ShortcodeTag:
This class is not new, just moved files. The two classmethods are new, though.

2022-03-22 20:19 UTC, ChristopherChudzicki commented on websites/management/commands/markdown_cleaning/link_parser.py
> +class LinkParser(WrappedParser):
This is where the main new logic is. A brief look at https://spec.commonmark.org/0.30/#links might be worthwhile, too. This parser does not handle all the CommonMark edge cases, but should be good enough for us.

#### Aside: Why not use a python libraring build for Markdown parsing?
Most of the pyparsing stuff was introduced in #1137 but adding it here for some context...

A specific Markdown library might be useful. The two reasons I shied away from that for now are (A) shortcodes and (B) my impression is that with a Markdown parsing library, we would need to:
1. for a single page, parse the **whole** markdown into HTML
2. make changes on the HTML
3. convert back to markdown

That's a global transformation: Ie, we'd be changing converting and unconverting all of the markdown to make localized edits. In principal it should be fine... the conversion process *should* be lossless. But I suspect there are a lot of quirks involved... `-` vs `*` for lists, `_` vs `*` for italics, inclusion (or not) of extra whitespace... All of those things *shouldn't* matter, but... they might. And I'd rather not tempt fate.

In contrast, Pyparsing lets us make localized transformations of the markdown text. We can change a link in the middle and be confident that the pragraphs above and below did not change **at all**.

2022-03-24 19:42 UTC, gumaerc requested changes
I spent a lot of time going over this and making sure I understand how `pyparsing` works and is being used here.  Overall this works very well at resolving `resolveuid` links and all the ones I manually went through ended up pointing at the right content.  I noted a few things below, and also noticed something interesting in the content itself.  I'm not sure if we can address this using markdown, but I noticed that there were some links like this:

`"[Functions of Two Variables Mathlet](./resolveuid/e1585460781926f359c7b54ce97984d3 ""Open in a new window."")","[Functions of Two Variables Mathlet](./resolveuid/e1585460781926f359c7b54ce97984d3 ""Open in a new window."")","False","markdown","18-02sc-multivariable-calculus-fall-2010","18.02sc-fall-2010","47187485-2c83-ac55-1b87-dcff9cb3f6cc","/courses/18-02sc-multivariable-calculus-fall-2010/pages/2.-partial-derivatives/part-a-functions-of-two-variables-tangent-approximation-and-optimization/session-30-second-derivative-test","False","","","UUID('e1585460-7819-26f3-59c7-b54ce97984d3')"`

You can see that some of these links have "Open in a new window." appended to the end of the URL for some reason.  There's no way to do a `target="_blank"` in markdown and it's out of scope for this PR, but in the future we might want to consider writing a shortcode for `target="_blank"`.  My main question here has to do with the fact that non `resolveuid` links show up in the results at all and I'm wondering why that is:

2022-03-24 19:42 UTC, gumaerc commented on websites/management/commands/markdown_cleaning/resolveuid_rule.py
> +        return "resolveuid" in text
First of all, I think the docstring here should describe that it's filtering on `resolveuid` in this case.  Secondly, why is it that I see non `resolveuid` links in the output labeled with the text set above "not a resolveuid link?"  Shouldn't `should_parse` be filtering those out?  I'm a little confused as to why anything other than `resolveuid` links are matched here.

2022-03-24 19:42 UTC, gumaerc commented on websites/management/commands/markdown_cleaning/utils.py
> +    Return True if text is valid uuid, esle False
typo: else

2022-03-24 20:19 UTC, ChristopherChudzicki commented
> "[Functions of Two Variables Mathlet](./resolveuid/e1585460781926f359c7b54ce97984d3 ...

Hey, you found the java applet we were talking about this morning! You likely noticed this, but there were a handful of resolveuid links where the uuid could not be resolved in OCW Next. Presumably this content was not migrated. In this particular case... the applet doesn't work anyway even [on the legacy site](https://ocw.mit.edu/courses/mathematics/18-02sc-multivariable-calculus-fall-2010/2.-partial-derivatives/part-a-functions-of-two-variables-tangent-approximation-and-optimization/problem-set-4/MIT18_02SC_ps4_applet.html). _Well, maybe it would for you on your retro 90s gaming computer 😄 _

> ...but in the future we might want to consider writing a shortcode for target="_blank"
We could certainly do that. I wonder if we could come up with rules like

- all links external to OCW open in a new tab (or maybe external to the current course site?) 
- links to root resources (not pages) open in a new tab (maybe??? unsure)

if we had rules like that, we could handle it with a Hugo renderHook.

Do ~normal people~ non-developers use ctrl+click / cmd+click to open links in new tabs? If so this functionality may be less compelling than it was in the early days of ocw.

> I'm a little confused as to why anything other than resolveuid links are matched here.

Does the updated docstring (for the abstract class) clear things up?

I agree this is slightly confusing.

I added a CLI option `--csv-only-changes` to only include changed matches in the CSV, which might be easier for people reviewing... _I did not want to do this by default. The unchanged matches can be very useful._

TY again for review.

2022-03-24 21:43 UTC, gumaerc approved these changes
:+1: LGTM

2022-03-24 21:49 UTC, merged