Hid Site Dashboard and refactored component
mitodl/ocw-studio pull request #1332
Opened 2022-05-12 12:21 UTC by Wassaf-Shahzad

#### Pre-Flight checklist

- [x] Screenshots and design review for any changes that affect layout or styling
- [x] Testing
  - [x] Changes have been manually tested

#### What are the relevant tickets?
Closes #1303 

#### What's this PR do?
Hides SiteDashboard in case of anonymous user 

#### How should this be manually tested?
- Open ocw-studio home page.
- Sign out if you are logged in.
-  Click ocw-studio logo.
- Verify SiteDashboard is not displayed.
- Verify Login Required is rendered. 

#### Screenshots (if appropriate)
<img width="1440" alt="Screenshot 2022-05-12 at 5 15 31 PM" src="https://user-images.githubusercontent.com/87968618/168073155-d34065e6-0fd9-419d-8b12-4202baab9835.png">

2022-05-12 13:22 UTC, Wassaf-Shahzad commented on static/js/pages/App.tsx
> +            <Route exact path="/sites">
Good Idea! Although I do have some thoughts. We should create ProtectedRoute as you say but shouldn't we inform the user in some way that he needs to login?
PS My first approach was to redirect the user but the redirect was soo seamless that it looked like the clicking the logo did nothing

2022-05-12 13:54 UTC, ChristopherChudzicki commented on static/js/pages/App.tsx
> +            <Route exact path="/sites">
>  We should create ProtectedRoute as you say but shouldn't we inform the user in some way that he needs to login?

Hmm, that's a good point. I just took a quick look at popular sites for reference... View these in a private browser if you're logged in for any of them 
1. https://www.linkedin.com/ ... has a logo at top which redirects to login
2. https://github.com/ ... has a log at top which redirects to login 
3. https://github.com/ ... has an extremely blatant "login" page with no links / options

The fact that (1) and (2) redirect to login without an alert makes me feel a better about us doing that. [Facebook's approach seems best to me, but would be way too big a change.]

IMO, redirecting to login with a <ProtectedRoute /> component seems more reusable + good separation of concerns, and the "too seamless redirect" issue is only an issue from the homepage. So I would go with the seamless login redirect.

2022-05-13 08:21 UTC, Wassaf-Shahzad commented on static/js/pages/App.tsx
> +            <Route exact path="/sites">
Ok thank you

2022-05-13 13:40 UTC, ChristopherChudzicki requested changes
👍 Looks good other than than the outdated comment

2022-05-16 07:18 UTC, merged