improve legacy shortcode handling
mitodl/ocw-studio pull request #1349
Opened 2022-05-16 16:10 UTC by ChristopherChudzicki

This builds on #1347 so waiting for that to be reviewed first.

#### Pre-Flight checklist

- [x] Testing
  - [x] Code is tested
  - [x] Changes have been manually tested

#### What are the relevant tickets?
#1317 

#### What's this PR do?
This improves the LegacyShortcodes plugin for CKEditor. "Legacy" Shortcodes are shortcodes that cannot be edited or created in Studio, i.e., only exist due to the migration of legacy content. Alice did some work so that we could safely edit pages containing such legacy shortcodes. This PR uses the some of the work from #1347  to improve upon this in two ways:
1. Some legacy shortcodes included shortocdes inside shortcodes (see image gallery item below)
2. Makes closing shortcodes a bit more flexible. The old code expected `{{< /shortcode-name...`. But some shortcodes, particularly image-gallery-item, used `{{</ shortcode-name`, ie with no space between "<" and "/". _Hugo documentation uses the first form, but Hugo itself tolerates both forms as closing shrotcode tags._

Both changes can be seen the screenshots below:

Before / After:
<img width="300" alt="Screen Shot 2022-05-16 at 12 03 46 PM" src="https://user-images.githubusercontent.com/9010790/168635881-bfb1d5d7-8aae-4e58-bf57-d09c6b8bfd19.png"> / <img width="300" alt="Screen Shot 2022-05-16 at 12 03 32 PM" src="https://user-images.githubusercontent.com/9010790/168635910-a1c3f007-c139-4e80-9027-62a21d1f7261.png">

#### How should this be manually tested?
Manually insert some legacy shortcodes into a content page and check that the page (but not the shortcodes themselves) can still be edited safely. The shortcode parameters should not change when editing. _Note for testing: the actual argument values don't need to be valid for those shortcodes since studio doesn't use the values._

For example:
```

Cyclosilicates
--------------
{{< image-gallery id="8d434783-38e4-6c38-89ad-01e859532b7e_nanogallery2" baseUrl="/courses/12-108-structure-of-earth-materials-fall-2004/" >}}
{{< image-gallery-item href="2237ca98fc40c772cac4af3df1e8635f_lab2-17.jpg" data-ngdesc="Beryl: Be3Al2Si6O18. Courtesy of OCW." text="Beryl: Be{{< sub 3 >}}Al{{< sub 2 >}}Si{{< sub 6 >}}O{{< sub 18 >}}." >}}
{{< image-gallery-item href="81ba381fade05dbad91194b41151d575_lab2-18.jpg" data-ngdesc="Tourmaline single crystal and tourmalines in quartz: NaMg3Al5B3Si6O27(OH)4. Courtesy of OCW." text="Tourmaline single crystal and tourmalines in quartz: NaMg{{< sub 3 >}}Al{{< sub 5 >}}B{{< sub 3 >}}Si{{< sub 6 >}}O{{< sub 27 >}}(OH){{< sub 4 >}}." >}}
{{< image-gallery-item href="1d7abc15a62bbec93420b7dcfa6ec674_lab2-19.jpg" data-ngdesc="Radiating acicular tourmaline crystals and tourmaline crystal in quartz: NaMg3Al5B3Si6O27(OH)4." text="Radiating acicular tourmaline crystals and tourmaline crystal in quartz: NaMg{{< sub 3 >}}Al{{< sub 5 >}}B{{< sub 3 >}}Si{{< sub 6 >}}O{{< sub 27 >}}(OH){{< sub 4 >}}." >}}
{{</ image-gallery >}}
```

2022-05-16 16:10 UTC, ChristopherChudzicki commented
Here's a complete list of legacy shortcod examples:
```
opening: {{< quiz_choice arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /quiz_choice foo="arg1" bar="arg2" >}}

opening: {{< quiz_choices arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /quiz_choices foo="arg1" bar="arg2" >}}

opening: {{< quiz_multiple_choice arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /quiz_multiple_choice foo="arg1" bar="arg2" >}}

opening: {{< quiz_solution arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /quiz_solution foo="arg1" bar="arg2" >}}

opening: {{< resource_file arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /resource_file foo="arg1" bar="arg2" >}}

opening: {{< video-gallery arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /video-gallery foo="arg1" bar="arg2" >}}

opening: {{< youtube arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /youtube foo="arg1" bar="arg2" >}}

opening: {{< anchor arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /anchor foo="arg1" bar="arg2" >}}

opening: {{< approx-students arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /approx-students foo="arg1" bar="arg2" >}}

opening: {{< br arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /br foo="arg1" bar="arg2" >}}

opening: {{< div-with-class arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /div-with-class foo="arg1" bar="arg2" >}}

opening: {{< fullwidth-cell arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /fullwidth-cell foo="arg1" bar="arg2" >}}

opening: {{< h arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /h foo="arg1" bar="arg2" >}}

opening: {{< image-gallery-item arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /image-gallery-item foo="arg1" bar="arg2" >}}

opening: {{< image-gallery arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /image-gallery foo="arg1" bar="arg2" >}}

opening: {{< quote arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /quote foo="arg1" bar="arg2" >}}

opening: {{< simplecast arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /simplecast foo="arg1" bar="arg2" >}}

opening: {{< sub arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /sub foo="arg1" bar="arg2" >}}

opening: {{< sup arg1 "{{< sup 2 >}}" >}} ... and now closing {{< /sup foo="arg1" bar="arg2" >}}

```

2022-05-18 13:52 UTC, mbertrand requested changes
After editing a page with the sample shortcodes, I noticed that those with an `data-ngdesc` attribute had been modified slightly to `ngdesc`.  I'm not sure what the repercussions of this change are, but I'm assuming the attribute name should remain the same.

From:
```
{{< image-gallery-item href="2237ca98fc40c772cac4af3df1e8635f_lab2-17.jpg" data-ngdesc="Beryl: Be3Al2Si6O18. Courtesy of OCW." text="Beryl: Be{{< sub 3 >}}Al{{< sub 2 >}}Si{{< sub 6 >}}O{{< sub 18 >}}." >}}  

```

To:
```
{{< image-gallery-item href="2237ca98fc40c772cac4af3df1e8635f_lab2-17.jpg" ngdesc="Beryl: Be3Al2Si6O18. Courtesy of OCW." text="Beryl: Be{{< sub 3 >}}Al{{< sub 2 >}}Si{{< sub 6 >}}O{{< sub 18 >}}." >}}
```

2022-05-18 16:07 UTC, ChristopherChudzicki commented
@mbertrand Good catch 👍  Is fixed.

2022-05-18 17:20 UTC, mbertrand approved these changes
Works great 👍

2022-05-18 17:25 UTC, merged