Switch to github actions
mitodl/ocw-studio pull request #15
Opened 2021-01-13 15:56 UTC by noisecapella

Fixes #5

2021-01-13 18:32 UTC, rhysyngsun commented
@noisecapella looks like it still failed?

2021-01-13 21:51 UTC, noisecapella commented
@rhysyngsun got it figured out, ready for review now

2021-01-13 22:02 UTC, rhysyngsun requested changes
One small thing

2021-01-13 22:02 UTC, rhysyngsun commented on requirements.txt
> +ipython==7.19.0           # via -r /home/george/Projects/ocw-studio/ocw_studio/ocw_studio/requirements.in
This has your full local path in it

2021-01-14 15:16 UTC, noisecapella commented
@rhysyngsun I ran pip-compile again and that should make my local path go away. However there are lots of indentation changes. I think that's just what pip-compile does now as their example on the readme at https://github.com/jazzband/pip-tools is formatted the same way

2021-01-14 16:50 UTC, rhysyngsun approved these changes

2021-01-14 16:54 UTC, merged