Implement select widget
mitodl/ocw-studio pull request #151
Opened 2021-03-24 20:08 UTC by noisecapella

#### Pre-Flight checklist

- [ ] Screenshots and design review for any changes that affect layout or styling
  - [ ] Desktop screenshots
  - [ ] Tag @ferdi or @pdpinch for review
- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Fixes #140 

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Screenshots (if appropriate)
![Screenshot from 2021-03-24 15-41-52](https://user-images.githubusercontent.com/863262/112376657-1ab87000-8cbb-11eb-9e62-77ffb4757660.png)

2021-03-25 18:01 UTC, gsidebo requested changes

2021-03-25 18:01 UTC, gsidebo commented on websites/serializers.py
> +                        )
Most/all of these validations seem to be for request data that should not be possible coming from the front end. I can think of a scenario where the data we get does not match the config fields – a user loads a content form with some site config, that config is updated on the backend, then the user submits the form. That's a larger issue that we need to address comprehensively, though. Adding this validation is jumping the gun, IMO. Lmk if I'm missing something

2021-03-25 18:01 UTC, gsidebo commented on websites/factories.py
> +        )["course"]
Use `COURSE_STARTER_SLUG`

2021-03-30 17:14 UTC, aliceriot commented
I'm seeing a validation issue where it says 'Tags is a required field' even though there is a value there:

![Screenshot from 2021-03-30 13-12-56](https://user-images.githubusercontent.com/6207644/113028888-ccdbb600-9159-11eb-8d89-47b00e6eb837.png)
![Screenshot from 2021-03-30 13-12-23](https://user-images.githubusercontent.com/6207644/113028900-cf3e1000-9159-11eb-9ddd-961960d41d6f.png)

I used the `override_site_configs` management command.

2021-03-31 16:25 UTC, aliceriot commented
word, just tried it and it looks good. I think we don't want tags to be a required field anyhow.

2021-03-31 17:58 UTC, aliceriot requested changes
a few comments / questions

2021-03-31 17:58 UTC, aliceriot commented on static/js/components/widgets/SelectField.test.tsx
> +      )
could be helpful to write a simple `render` function to DRY up the test cases a little bit

2021-03-31 17:58 UTC, aliceriot commented on static/js/components/widgets/SelectField.tsx
> +  }
probably a good idea to wrap this function with `useCallback`

2021-03-31 17:58 UTC, aliceriot commented on static/js/components/widgets/SelectField.tsx
> +      // @ts-ignore
I don't see any errors if I delete this `@ts-ignore`

2021-03-31 17:58 UTC, aliceriot commented on static/js/lib/site_content.ts
> +  values: Record<string, any>,
is there any way we can avoid `any` here?

2021-03-31 17:58 UTC, aliceriot commented on static/js/lib/site_content.ts
> +  values: Record<string, any>,
I changed it to `Record<string, string | File>` and didn't get any type errors except for one in a test file

2021-03-31 20:15 UTC, aliceriot approved these changes
lgtm! :+1:

2021-03-31 20:18 UTC, merged