Course publish without metadata
mitodl/ocw-studio pull request #2015
Opened 2023-11-01 07:21 UTC by Anas12091101

# What are the relevant tickets?
Fixes #1996 

# Description (What does it do?)
You can add content to a course and publish it in staging without ever visiting the Metadata section. Production, however will require metadata to be set.

# Screenshots (if appropriate):
<img width="1430" alt="Screenshot 2023-10-20 at 2 34 36 PM" src="https://github.com/mitodl/ocw-studio/assets/88967643/8ec2c92a-5f58-475e-9a5a-2e7424861c6b">
<img width="1145" alt="Screenshot 2023-10-20 at 2 35 37 PM" src="https://github.com/mitodl/ocw-studio/assets/88967643/c422612f-20c9-4a41-90cd-1fb9bd5aacd6">
<img width="1440" alt="Screenshot 2023-10-20 at 2 35 51 PM" src="https://github.com/mitodl/ocw-studio/assets/88967643/0189d6ca-5594-47cf-b9cc-2bfd6912402a">

# How can this be tested?
- Clone this [branch](https://github.com/Anas12091101/ocw-studio/tree/Issue_metadata) from my forked repo
- Restart studio containers
- Go to the studio website at http://localhost:8043/admin and login as admin
- Create a new site with **ocw-course** starter
- (Optional) Add pages to the website
- Open the publish drawer, you can see that the publish button is enabled in the staging and disabled in production (as we have not set metadata yet)
- Press the publish button in staging
- After the pipeline finishes, you get the published website on the url

# Additional Context
The `course-v2/layouts/partials/course_banner.html` file was changed in the `ocw-hugo-themes` repository. You can view the changes [here](https://github.com/mitodl/ocw-hugo-themes/pull/1274/files)

2023-11-06 12:10 UTC, HussainTaj-arbisoft reviewed
Can we add or update the tests in `websites/serializers_test.py` to ensure that a value for `has_site_metadata` is serialized and present?

Similarly, should we add or update tests in `static/js/components/PublishDrawer.test.tsx`?

2023-11-07 06:36 UTC, HussainTaj-arbisoft reviewed
Can we also add a warning message in `websites/api.py get_content_warnings`?

For example

```py
    if not website.has_site_metadata:
        messages.append(
            "The course is missing metadata."
        )
```

> website.has_site_metadata is a property on the model class. Just for the sake of reusability.

2023-11-07 10:58 UTC, Anas12091101 commented
> Can we add or update the tests in `websites/serializers_test.py` to ensure that a value for `has_site_metadata` is serialized and present?
> 
> Similarly, should we add or update tests in `static/js/components/PublishDrawer.test.tsx`?

2023-11-08 11:24 UTC, HussainTaj-arbisoft requested changes

2023-11-08 11:24 UTC, HussainTaj-arbisoft commented on websites/api.py
> +    if not bool(site_metadata and site_metadata[0].metadata):
Please also update the unit tests for this method.

2023-11-15 06:23 UTC, HussainTaj-arbisoft commented
I will reopen it to trigger CI.

2023-11-15 07:37 UTC, Anas12091101 commented on static/js/components/PublishDrawer.test.tsx
> +          expect(wrapper.find(".btn-publish").prop("disabled")).toBe(true)
yes, will update it

2023-11-15 07:37 UTC, Anas12091101 commented on static/js/types/websites.ts
> +  has_site_metadata: boolean
yes, you are right

2024-04-01 07:40 UTC, Anas12091101 commented
@HussainTaj-arbisoft Can I close this PR?

2024-05-17 09:48 UTC, ibrahimjaved12 commented
Recreated the PR here without fork, to get all checks up and running: https://github.com/mitodl/ocw-studio/pull/2183

2024-05-17 09:48 UTC, closed without merging