WIP enhanced testing pipeline
mitodl/ocw-studio pull request #2018
Opened 2023-11-06 23:36 UTC by gumaerc

# What are the relevant tickets?

# Description (What does it do?)

# Screenshots (if appropriate):

- [ ] Desktop screenshots
- [ ] Mobile width screenshots

# How can this be tested?

# Additional Context

2023-12-01 22:24 UTC, gumaerc commented
@HussainTaj-arbisoft Thanks for your reviews. I took some of your suggestions and did the following:

 - `STATIC_API_BASE_URL_TEST` when running the pipeline locally needs to be the Docker IP of your nginx instance on the correct port. I made some changes to `content_sync/utils/get_common_pipeline_vars` to set the correct defaults, but for what it's worth that ends up being http://10.1.0.102:8046. In a browser you can access this at http://localhost:8046 because of port forwarding, but Concourse needs to access it through the Docker IP.
 - I altered the `docker-compose.yml` to create the test buckets
 - @ChristopherChudzicki pointed out that once this gets deployed to RC and production, the test sites will show up in the "new courses" section. This will cause the `ocw-www` build to fail, because the test sites aren't actually deployed to the publish bucket. I modified the API view sets to exclude the test sites based on `OCW_WWW_TEST_SLUG` and `OCW_COURSE_TEST_SLUG`.
 - I committed the fixtures to the repo under `test_site_fixtures`
 - I added a section to the readme about how to set up the pipeline locally

2023-12-04 12:39 UTC, HussainTaj-arbisoft requested changes
@gumaerc, thank you for the updates. I got the pipeline up and running.

The tests are failing because of a URL mismatch in the fixtures and tests. I left a separate comment denoting an instance of the fixture that should be changed.

Here's a log of the `playwright-task` step, just in case: 
[playwright-task.log](https://github.com/mitodl/ocw-studio/files/13545939/playwright-task.log)

---

You might also be interested in this side note. I had my Docker setup with 8 GB memory. While running the e2e tests pipeline, my docker kept crashing. After I upgraded my docker's allocated memory to 10 GB, things started to work.

It's not in the scope of this ticket, but perhaps in the future, we might consider reducing the number of playwright workers for local development.

2023-12-04 12:39 UTC, HussainTaj-arbisoft commented on test_site_fixtures/test_website_content.json
> +      "file": "courses/123-ocw-ci-test-course-fall-2022/example_jpg.jpg"
These need to be updated. https://github.com/mitodl/ocw-hugo-themes/pull/1280 changes expected urls from `.../123-ocw-ci-test-course-fall-2022/...` to `.../ocw-ci-test-course/...`.

The content generated from these fixtures fails tests.

2023-12-04 15:29 UTC, gumaerc commented
@HussainTaj-arbisoft I updated the url path of the offending files in the test site fixtures

2023-12-05 12:54 UTC, HussainTaj-arbisoft requested changes
@gumaerc, thanks for the updates. The fixtures seem correct now and some of the failing tests have started passing.

The test pipeline now fails for `file` fields.

```log
    Expected string: "https://10.1.0.102:8046/courses/ocw-ci-test-course/example_jpg.jpg"
    Received string: "https://10.1.0.102:8046/media/courses/ocw-ci-test-course/example_jpg.jpg"
```

I don't know where this `media` is coming from in the [synced content](https://github.com/hussaintaj-mitodl/ocw-ci-test-course/blob/main/content/resources/example_jpg.md). It might be either something wrong with my environment or this might be how local publishes work. Would you know anything about it?

---

PS: Left a couple of other comments.

2023-12-06 12:58 UTC, HussainTaj-arbisoft reviewed
Thank you, @gumaerc. I got the green lights 🎉 

I've left a few more questions and suggestions.

2023-12-07 01:01 UTC, gumaerc commented
@HussainTaj-arbisoft I was able to address everything you noted above, but was not able to finish the unit tests tonight. I'll get that done first thing tomorrow morning.

2023-12-11 09:26 UTC, HussainTaj-arbisoft approved these changes
LGTM 👍 

I read the comment about dealing with WebsiteStarter fixtures later. That sounds okay to me.

2023-12-20 21:49 UTC, merged