Multiple open catalog webhook endpoints
mitodl/ocw-studio pull request #2071
Opened 2024-01-16 19:30 UTC by mbertrand

### What are the relevant tickets?
Closes #1994

### Description (What does it do?)

### Screenshots (if appropriate):

- [ ] Desktop screenshots
- [ ] Mobile width screenshots

### How can this be tested?

### Additional Context

2024-01-17 14:55 UTC, mbertrand commented on content_sync/pipelines/definitions/concourse/theme_assets_pipeline.py
> +    ]
@gumaerc can this variable be removed? It doesn't seem to be used anywhere in the pipeline.

2024-01-17 22:50 UTC, gumaerc requested changes
This looks good aside from a couple unnecessary resource definitions, one of which you already noted. Another thing I wanted to mention is that when I test non-dev things like this, instead of changing my environment in my `.env` file, I usually go in and temporarily remove the if statements limiting the steps in question to dev only. This means we can test pushing the pipeline up to our local Concourse instance and run it, and the pipeline will mostly work as expected. This doesn't work for things like testing Fastly cache clearing (although it might with the proper vars in place) but for something like this Open Discussions / MIT Open will accept the webhook request as long as you have the proper key. I tested all of the pipelines in question here that way and all looks good. I did get a 503 when it went to hit MIT Open but that looks to be because as of the time of writing this, the database is down or improperly configured. I will test again once it's back up.

2024-01-18 17:29 UTC, mbertrand commented on content_sync/pipelines/definitions/concourse/theme_assets_pipeline.py
> +    ]
Removed

2024-01-18 18:17 UTC, gumaerc commented
Testing this again, the remove-unpublished-sites pipeline fails trying to hit https://mit-open-rc.odl.mit.edu/api/v0/ocw_next_webhook/ with a 404

2024-01-18 18:59 UTC, gumaerc commented on main/settings.py
> +OPEN_CATALOG_URLS = get_delimited_list(
Can we add example values for these new settings in `.env.example`, and document their usage in `README.md`?

2024-01-18 19:44 UTC, gumaerc approved these changes
:+1: 

Looks good to me now, although wait to merge this until the new env settings are fully deployed all the way to production.

2024-01-18 20:11 UTC, merged