add the get_destination_url helper function and use it for menu urls
mitodl/ocw-studio pull request #496
Opened 2021-08-16 22:11 UTC by gumaerc

#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Closes https://github.com/mitodl/ocw-studio/issues/493

#### What's this PR do?
In https://github.com/mitodl/ocw-studio/pull/425 and https://github.com/mitodl/ocw-studio/pull/364 we added backend support for generating a Hugo nav menu configuration.  A file path to a piece of content's markdown was used for the `url` property, when in reality what is expected here is a URL; relative for internal, absolute for external.  This PR adds a helper function called `get_destination_url` that generates the expected relative URL of a piece of content in a rendered site and uses it in the Hugo menu serializer.

#### How should this be manually tested?
 - Spin up `ocw-studio` locally on this branch and make sure you are set up to sync to github.mit.edu
 - Make sure you have a website starter that includes a nav menu widget, like https://github.com/mitodl/ocw-hugo-projects/blob/main/ocw-course/ocw-studio.yaml
 - Create a website using this starter
 - Add some pages or other pieces of content that can be linked to internally
 - Add some menu entries that point to this content you've created
 - Publish your site and inspect `config/_default/menus.yaml`, the URL properties should now not contain the `content/` prefix nor the `.md` file extension

2021-08-17 15:01 UTC, noisecapella commented
FYI I found this bug when testing this issue, where URLs are not generated on output at all. https://github.com/mitodl/ocw-studio/issues/497. Were you able to reproduce this PR on your laptop?

2021-08-17 19:11 UTC, gumaerc commented
> FYI I found this bug when testing this issue, where URLs are not generated on output at all. #497. Were you able to reproduce this PR on your laptop?

I checked this out and yea, I see that after updating the menu items they have no `url` property and only `identifier` with the UUID.  I think you are correct in that internally we should only be storing the UUID and then upon exporting a course to Github, use `get_destination_url` to generate the URL.  Either way, `get_destination_url` uses `content.dirpath` as the base for building the URL, so that shouldn't really matter.  I think maybe `ocw_import.api.import_ocw2hugo_menu` should just conform with the version 4 UUID in that case as you showed in the issue, because it's not currently doing that on import:

```
menu_data["leftnav"][i]["identifier"] = str(
                uuid.UUID(menu_data["leftnav"][i]["identifier"])
            )
```

`url` is imported simply because `ocw-to-hugo` generates the URL and puts it into `menus.yaml`, and since all of the properties of all menu items are imported as metadata it's brought in alongside everything else.

2021-08-17 23:03 UTC, gumaerc commented
@noisecapella I added some additional transformation that was necessary, stripping away the website slug as well as `_index` from index pages, and I reformatted for readability.  Based on our discussion, I commented on the other issue with `is_valid_uuid` and will follow up on that tomorrow.

2021-08-18 17:35 UTC, noisecapella requested changes

2021-08-18 17:35 UTC, noisecapella commented on content_sync/utils.py
> +        dirpath = content.dirpath.replace(content.website.name, "", 1)
Can we combine this line and the next one, and also check that the search string is a prefix?

    prefix = f'{content.website.name}/{site_config.content_dir}'
    if content.dirpath.startswith(prefix):
        dirpath = content.dirpath.replace(prefix, "", 1)

2021-08-18 18:08 UTC, noisecapella commented
Functionality works great after I made the edit to `is_valid_uuid`

2021-08-19 20:23 UTC, gumaerc commented
@noisecapella all cleaned up

2021-08-20 13:39 UTC, noisecapella approved these changes

2021-08-20 13:59 UTC, merged