Only show "Add resource" button when attach field is set
mitodl/ocw-studio pull request #530
Opened 2021-08-30 16:26 UTC by noisecapella

#### Pre-Flight checklist

- [ ] Testing
  - [ ] Code is tested
  - [ ] Changes have been manually tested

#### What are the relevant tickets?
Fixes #529 

#### What's this PR do?
Hides the Add resource button 

#### How should this be manually tested?
For any of the imported courses, add a new page. You should see a "Add resource" button in the "Body" section of the UI. Click it and a modal should show up.

Go to the site metadata for the same course. You should not see an "Add resource" button on the course description field.

2021-08-30 17:45 UTC, alicewriteswrongs requested changes
two questions / suggestions

2021-08-30 17:45 UTC, alicewriteswrongs commented on static/js/components/widgets/MarkdownEditor.tsx
> +          // @ts-ignore
I think you can get rid of the `@ts-ignore` here if you inline the value of `hasAttach` (`attach && attach.length > 0`) - I think typescript is just not quite smart enough to figure that one out

you could also probably do an `attach as string` type coercion

2021-08-30 17:45 UTC, alicewriteswrongs commented on static/js/components/widgets/MarkdownEditor.tsx
> +            hasAttach ? true : item !== ADD_RESOURCE
maybe `hasAttach || item !== ADD_RESOURCE` ?

2021-08-31 18:50 UTC, noisecapella commented
@alicewriteswrongs comments addressed

2021-08-31 19:07 UTC, alicewriteswrongs approved these changes
lgtm! 👍

2021-08-31 19:08 UTC, merged